console.log('tusk 1');
let name = 'Генератор защитного поля';
let cost = '1000';
// console.log('Выбран', '«', name, '»',);
console.log('Выбран', '«', name,',', '»','цена за штуку',  cost, 'кредитов') ;
cost = 2000;
console.log('Выбран', '«', name,',', '»','цена за штуку',  cost, 'кредитов') ;
console.log('tusk 2');
let enterName = prompt('userName');
let greeting = prompt('greeting');
console.log(enterName,',',greeting);